name: ${APP_NAME}
services:
    webserver:
        container_name: ${APP_NAME}-webserver
        image: nginx:alpine
        working_dir: /var/www/
        volumes:
            - ../:/var/www/
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${APP_DOCKER_PORT}:80
        depends_on:
            - app
        env_file:
            - ".env"
    app:
        build:
            context: ./php/.
            args:
                APP_DEBUG: ${APP_DEBUG}
        container_name: ${APP_NAME}-app
        working_dir: /var/www/
        volumes:
            - ../:/var/www/
            - ./php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        depends_on:
            - mysql
        env_file:
            - ".env"
    mysql:
        container_name: ${APP_NAME}-mysql
        image: mysql:latest
        ports:
            - ${MYSQL_DOCKER_PORT}:${MYSQL_PORT}
        environment:
            MYSQL_TCP_PORT: ${MYSQL_PORT}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        env_file:
            - ".env"
    postgres:
        container_name: ${APP_NAME}-postgres
        image: postgres:latest
        command: -p ${POSTGRES_PORT}
        ports:
            - ${POSTGRES_DOCKER_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - ".env"
volumes:
    mysql:
    postgres:

